// DB 行（snake_case）→ 前端类型（camelCase）。金额保持字符串，时间为 ISO 字符串。

export const mapCustomer = (r: any) => ({
  customerId: r.customer_id,
  name: r.name,
  refCompanyId: r.ref_company_id,
  organizationId: r.organization_id,
  category: r.category,
  level: r.level_term_id,
  source: r.source_term_id,
  currentTrackingStatus: r.status_term_id,
  poolGroup: r.pool_group_term_id,
  industry: r.industry,
  province: r.province,
  city: r.city,
  district: r.district,
  origin: r.origin,
  labels: r.labels ?? [],
  phoneName: r.phone_name,
  phone: r.phone,
  email: r.email,
  trackingNum: r.tracking_num,
  trackingUpdateDate: r.tracking_update_at,
  nextTrackingDate: r.next_tracking_at,
  leaderId: r.leader_id,
  preLeaderId: r.pre_leader_id,
  loseTime: r.lose_time,
  opportunityCount: r.opportunity_count,
  approval: r.approval,
  active: r.active,
  createDate: r.created_at,
});

export const mapContact = (r: any) => ({
  contactId: r.contact_id,
  customerId: r.customer_id,
  name: r.name,
  phone: r.phone,
  email: r.email,
  wechat: r.wechat,
  position: r.position,
  department: r.department,
  type: r.type,
  maintainerId: r.maintainer_id,
  sourceLeadsId: r.source_leads_id,
});

export const mapTracking = (r: any) => ({
  trackingId: r.tracking_id,
  customerId: r.customer_id,
  businessType: r.business_type,
  businessId: r.business_id,
  trackingType: r.tracking_type_term,
  comment: r.comment,
  nextTrackingDate: r.next_tracking_at,
  priorityLevel: r.priority_level,
  ding: r.ding ?? [],
  createBy: r.created_by,
  createDate: r.created_at,
});

export const mapOpportunity = (r: any) => ({
  opportunityId: r.opportunity_id,
  code: r.code,
  name: r.name,
  customerId: r.customer_id,
  customerName: r.customer_name,
  liaisonId: r.liaison_id,
  keyManId: r.key_man_id,
  estimatedAmount: r.estimated_amount,
  expiryDate: r.expiry_date,
  status: r.status_term_id,
  statusExpiryDate: r.status_expiry_at,
  allStayTime: r.all_stay_time,
  leaderId: r.leader_id,
  depId: r.department_id,
  competitor: r.competitor,
  mainProduct: r.main_product,
  renewType: r.renew_type,
  additional: r.additional,
  approval: r.approval,
  active: r.active,
  createDate: r.created_at,
});

export const mapQuotation = (r: any) => ({
  quotationId: r.quotation_id,
  code: r.code,
  version: r.version,
  sourceCode: r.source_code,
  name: r.name,
  customerId: r.customer_id,
  customerName: r.customer_name,
  contactId: r.contact_id,
  opportunityId: r.opportunity_id,
  bidderId: r.bidder_id,
  quoteDate: r.quote_date,
  expiredDate: r.expired_date,
  currency: r.currency,
  status: r.status,
  total: r.total,
  comDiscountRate: r.com_discount_rate,
  orderDiscountRate: r.order_discount_rate,
  otherCharges: r.other_charges,
  discount: r.discount,
  amount: r.amount,
  cost: r.cost,
  grossProfit: r.gross_profit,
  grossProfitRate: r.gross_profit_rate,
  approval: r.approval,
});

export const mapQuotationProduct = (r: any) => ({
  id: r.id,
  quotationId: r.quotation_id,
  productId: r.product_id,
  productName: r.product_name,
  spec: r.spec,
  quantity: r.quantity,
  price: r.price,
  discountRate: r.discount_rate,
  discountPrice: r.discount_price,
  totalPrice: r.total_price,
  cost: r.cost,
});

export const mapContract = (r: any) => ({
  contractId: r.contract_id,
  code: r.code,
  name: r.name,
  customerId: r.customer_id,
  customerName: r.customer_name,
  quotationId: r.quotation_id,
  opportunityId: r.opportunity_id,
  contractType: r.contract_type,
  parentContractId: r.parent_contract_id,
  renewType: r.renew_type,
  beginDate: r.begin_date,
  expiredDate: r.expired_date,
  currency: r.currency,
  status: r.status,
  amount: r.amount,
  receivedAmount: r.received_amount,
  outstandingAmount: r.outstanding_amount,
  badDebtsAmount: r.bad_debts_amount,
  receivedRate: r.received_rate,
  invoiceAmount: r.invoice_amount,
  notInvoiceAmount: r.not_invoice_amount,
  grossProfit: r.gross_profit,
  cashProfit: r.cash_profit,
  labels: r.labels ?? [],
  approval: r.approval,
  changeApproval: r.change_approval,
  archive: r.archive,
  leaderId: r.leader_id,
});

export const mapPayment = (r: any) => ({
  paymentId: r.payment_id,
  contractId: r.contract_id,
  contractCode: r.contract_code,
  customerId: r.customer_id,
  customerName: r.customer_name,
  planAmount: r.plan_amount,
  receivedAmount: r.received_amount,
  outstandingAmount: r.outstanding_amount,
  badDebtsAmount: r.bad_debts_amount,
  status: r.status,
  type: r.type_term_id,
  planDate: r.plan_date,
  leaderId: r.leader_id,
});

export const mapInvoice = (r: any) => ({
  invoiceId: r.invoice_id,
  code: r.code,
  contractId: r.contract_id,
  customerId: r.customer_id,
  customerName: r.customer_name,
  invoiceType: r.invoice_type_term,
  redBlueFlag: r.red_blue_flag,
  invoiceAttributes: r.invoice_attr,
  amount: r.amount,
  taxAmount: r.tax_amount,
  noTaxAmount: r.no_tax_amount,
  status: r.status,
  invoiceUrl: r.invoice_url,
  approval: r.approval,
  invalidApproval: r.invalid_approval,
  createDate: r.created_at,
});

export const mapPreCredit = (r: any) => ({
  preCreditId: r.pre_credit_id,
  contractId: r.contract_id,
  customerId: r.customer_id,
  customerName: r.customer_name,
  amount: r.amount,
  termDays: r.term_days,
  beginDate: r.begin_date,
  endDate: r.end_date,
  expectSignDate: r.expect_sign_date,
  expectReceiveDate: r.expect_receive_date,
  status: r.status,
  approval: r.approval,
});

export const mapProduct = (r: any) => ({
  productId: r.product_id,
  code: r.code,
  name: r.name,
  categoryId: r.category_id,
  categoryName: r.category_name,
  spec: r.spec,
  unit: r.unit,
  timeLimits: r.time_limits,
  active: r.active,
  freePricing: r.free_pricing,
  price: r.price,
  cost: r.cost,
  minDiscount: r.min_discount,
  maxDiscount: r.max_discount,
});

export const mapBackLog = (r: any) => ({
  backLogId: r.back_log_id,
  businessType: r.business_type,
  businessId: r.business_id,
  businessName: r.business_name,
  userId: r.user_id,
  status: r.status,
  deadlineDate: r.deadline_date,
  deadlineType: r.deadline_type,
  tipMsg: r.tip_msg,
});

export const mapTarget = (r: any) => ({
  targetId: r.target_id,
  userId: r.user_id,
  depId: r.department_id,
  year: r.year,
  month: r.month,
  category: r.category,
  targetAmount: r.target_amount,
  finishedAmount: r.finished_amount,
  newSignAmount: r.new_sign_amount,
  renewAmount: r.renew_amount,
});

export const mapTerm = (r: any) => ({
  termId: r.term_id,
  businessType: r.business_type,
  name: r.name,
  kind: r.kind ?? undefined,
  order: r.sort_order,
});
